-- Up
CREATE TABLE Student (
  id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
  studentName TEXT,
  credits INTEGER
);

CREATE TABLE Instructor (
  id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
  instructorName TEXT,
  department TEXT
);

CREATE TABLE Course (
  id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  instructorId INTEGER,
  FOREIGN KEY (instructorId) REFERENCES Instructor(id)
);

CREATE TABLE Enrollment (
  id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
  studentId INTEGER,
  courseId INTEGER,
  grade INTEGER,
  FOREIGN KEY (studentId) REFERENCES Student(id),
  FOREIGN KEY (courseId) REFERENCES Course(id)
);

-- Down
DROP TABLE Enrollment;
DROP TABLE Course;
DROP TABLE Instructor;
DROP TABLE Student;
